name: CI

on:
  push:

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          key: poetry-2.2.1
          path: ~/.local/

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        id: install-poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.2.1

      - name: Add Poetry to PATH
        id: add-poetry-path
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          key: python-${{ steps.setup-python.outputs.python-version }}-poetry-lock-${{ hashFiles('poetry.lock') }}-toml-${{ hashFiles('pyproject.toml') }}
          path: /home/runner/.cache/pypoetry/virtualenvs/

      - name: Install dependencies
        id: install-deps
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Run Black
        id: black
        run: poetry run black . --check

      - name: Run Ruff
        id: ruff
        run: |
          poetry run ruff check --select I
          poetry run ruff check

      - name: Run Mypy
        id: mypy
        run: poetry run mypy .

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          key: poetry-2.2.1
          path: ~/.local/

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        id: install-poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.2.1

      - name: Add Poetry to PATH
        id: add-poetry-path
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          key: python-${{ steps.setup-python.outputs.python-version }}-poetry-lock-${{ hashFiles('poetry.lock') }}-toml-${{ hashFiles('pyproject.toml') }}
          path: /home/runner/.cache/pypoetry/virtualenvs/

      - name: Install dependencies
        id: install-deps
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Run tests
        id: pytest
        run: |
          poetry run coverage run -m pytest .
          poetry run coverage report -m
